import json
from pathlib import Path

root = Path(__file__).resolve().parent

kanji_items = [
    {"id": "kanji-001", "type": "Kanji", "japanese": "一", "reading": "いち", "meaning": "one", "example": "一人です。", "jlpt": "N3", "categories": ["daily life", "school"]},
    {"id": "kanji-002", "type": "Kanji", "japanese": "二", "reading": "に", "meaning": "two", "example": "二つあります。", "jlpt": "N3", "categories": ["daily life", "school"]},
    {"id": "kanji-003", "type": "Kanji", "japanese": "三", "reading": "さん", "meaning": "three", "example": "三人います。", "jlpt": "N3", "categories": ["daily life", "school"]},
    {"id": "kanji-004", "type": "Kanji", "japanese": "四", "reading": "し / よん", "meaning": "four", "example": "四時です。", "jlpt": "N3", "categories": ["daily life", "school"]},
    {"id": "kanji-005", "type": "Kanji", "japanese": "五", "reading": "ご", "meaning": "five", "example": "五日です。", "jlpt": "N3", "categories": ["daily life", "school"]},
    {"id": "kanji-006", "type": "Kanji", "japanese": "六", "reading": "ろく", "meaning": "six", "example": "六月です。", "jlpt": "N3", "categories": ["daily life", "school"]},
    {"id": "kanji-007", "type": "Kanji", "japanese": "七", "reading": "しち / なな", "meaning": "seven", "example": "七つあります。", "jlpt": "N3", "categories": ["daily life", "school"]},
    {"id": "kanji-008", "type": "Kanji", "japanese": "八", "reading": "はち", "meaning": "eight", "example": "八時です。", "jlpt": "N3", "categories": ["daily life", "school"]},
    {"id": "kanji-009", "type": "Kanji", "japanese": "九", "reading": "きゅう / く", "meaning": "nine", "example": "九日です。", "jlpt": "N3", "categories": ["daily life", "school"]},
    {"id": "kanji-010", "type": "Kanji", "japanese": "十", "reading": "じゅう", "meaning": "ten", "example": "十人です。", "jlpt": "N3", "categories": ["daily life", "school"]},
    {"id": "kanji-011", "type": "Kanji", "japanese": "日", "reading": "にち / じつ", "meaning": "day / sun", "example": "今日はいい天気です。", "jlpt": "N3", "categories": ["daily life", "school"]},
    {"id": "kanji-012", "type": "Kanji", "japanese": "月", "reading": "げつ / つき", "meaning": "month / moon", "example": "月曜日です。", "jlpt": "N3", "categories": ["daily life", "school"]},
    {"id": "kanji-013", "type": "Kanji", "japanese": "火", "reading": "か", "meaning": "fire", "example": "火がつきました。", "jlpt": "N3", "categories": ["daily life", "school"]},
    {"id": "kanji-014", "type": "Kanji", "japanese": "水", "reading": "すい / みず", "meaning": "water", "example": "水を飲みます。", "jlpt": "N3", "categories": ["daily life", "school"]},
    {"id": "kanji-015", "type": "Kanji", "japanese": "木", "reading": "もく / き", "meaning": "tree / wood", "example": "木が高いです。", "jlpt": "N3", "categories": ["daily life", "school"]},
    {"id": "kanji-016", "type": "Kanji", "japanese": "金", "reading": "きん / かね", "meaning": "gold / money", "example": "お金が必要です。", "jlpt": "N3", "categories": ["daily life", "work"]},
    {"id": "kanji-017", "type": "Kanji", "japanese": "土", "reading": "ど / つち", "meaning": "earth / soil", "example": "土です。", "jlpt": "N3", "categories": ["daily life", "school"]},
    {"id": "kanji-018", "type": "Kanji", "japanese": "山", "reading": "さん / やま", "meaning": "mountain", "example": "山に行きます。", "jlpt": "N3", "categories": ["travel", "daily life"]},
    {"id": "kanji-019", "type": "Kanji", "japanese": "川", "reading": "せん / かわ", "meaning": "river", "example": "川を見ました。", "jlpt": "N3", "categories": ["travel", "daily life"]},
    {"id": "kanji-020", "type": "Kanji", "japanese": "人", "reading": "じん / ひと", "meaning": "person", "example": "人が多いです。", "jlpt": "N3", "categories": ["daily life", "school"]},
]

base_kanji = [
    ("大", "だい / おお", "big", ["daily life", "school"]),
    ("中", "ちゅう / なか", "middle / inside", ["daily life", "school"]),
    ("小", "しょう / ちい", "small", ["daily life", "school"]),
    ("田", "でん / た", "rice field", ["daily life", "school"]),
    ("文", "ぶん / ふみ", "sentence / literature", ["school", "daily life"]),
    ("本", "ほん / もと", "book / origin", ["school", "daily life"]),
    ("目", "もく / め", "eye", ["daily life", "school"]),
    ("耳", "じ / みみ", "ear", ["daily life", "school"]),
    ("口", "こう / くち", "mouth", ["daily life", "school"]),
    ("手", "しゅ / て", "hand", ["daily life", "school"]),
    ("足", "そく / あし", "foot", ["daily life", "school"]),
    ("立", "りつ / た", "stand", ["daily life", "school"]),
    ("走", "そう / はし", "run", ["daily life", "travel"]),
    ("休", "きゅう / やす", "rest", ["daily life", "school"]),
    ("先", "せん / さき", "before / ahead", ["school", "daily life"]),
    ("生", "せい / う", "life / birth", ["school", "daily life"]),
    ("友", "ゆう / とも", "friend", ["daily life", "school"]),
    ("学", "がく / まな", "study", ["school", "daily life"]),
    ("校", "こう / こう", "school", ["school", "daily life"]),
    ("何", "か / なに", "what", ["school", "daily life"]),
    ("住", "じゅう / す", "reside", ["daily life", "travel"]),
    ("使", "し / つか", "use", ["daily life", "work"]),
    ("送", "そう / おく", "send", ["daily life", "work"]),
    ("行", "こう / い", "go", ["daily life", "travel"]),
    ("来", "らい / く", "come", ["daily life", "travel"]),
    ("帰", "き / かえ", "return", ["daily life", "travel"]),
    ("分", "ぶん / わ", "part / understand", ["school", "daily life"]),
    ("開", "かい / ひら", "open", ["daily life", "work"]),
    ("閉", "へい / し", "close", ["daily life", "work"]),
    ("店", "てん / みせ", "shop", ["daily life", "work"]),
    ("食", "しょく / た", "eat", ["daily life", "school"]),
    ("飲", "いん / の", "drink", ["daily life", "school"]),
    ("寝", "しん / ね", "sleep", ["daily life", "school"]),
    ("起", "き / お", "wake up", ["daily life", "school"]),
    ("見", "けん / み", "see", ["daily life", "travel"]),
    ("聞", "ぶん / き", "hear", ["daily life", "school"]),
    ("話", "わ / はな", "talk", ["daily life", "school"]),
    ("書", "しょ / か", "write", ["school", "daily life"]),
    ("読", "どく / よ", "read", ["school", "daily life"]),
    ("思", "し / おも", "think", ["school", "daily life"]),
    ("考", "こう / かんが", "consider", ["school", "daily life"]),
    ("知", "ち / し", "know", ["school", "daily life"]),
    ("道", "どう / みち", "road", ["travel", "daily life"]),
    ("駅", "えき", "station", ["travel", "daily life"]),
    ("空", "くう / そら", "sky / empty", ["travel", "daily life"]),
    ("海", "かい / うみ", "sea", ["travel", "daily life"]),
    ("雨", "う / あめ", "rain", ["daily life", "travel"]),
    ("雪", "せつ / ゆき", "snow", ["daily life", "travel"]),
    ("風", "ふう / かぜ", "wind", ["daily life", "travel"]),
    ("花", "か / はな", "flower", ["daily life", "travel"]),
    ("草", "そう / くさ", "grass", ["daily life", "travel"]),
    ("森", "しん / もり", "forest", ["daily life", "travel"]),
    ("石", "せき / いし", "stone", ["daily life", "travel"]),
    ("町", "ちょう / まち", "town", ["daily life", "travel"]),
    ("国", "こく / くに", "country", ["travel", "daily life"]),
    ("内", "ない / うち", "inside", ["daily life", "school"]),
    ("外", "がい / そと", "outside", ["daily life", "school"]),
    ("前", "ぜん / まえ", "front", ["daily life", "travel"]),
    ("後", "ご / うし", "behind", ["daily life", "travel"]),
    ("左", "さ / ひだり", "left", ["daily life", "travel"]),
    ("右", "う / みぎ", "right", ["daily life", "travel"]),
    ("上", "じょう / うえ", "above", ["daily life", "travel"]),
    ("下", "か / した", "below", ["daily life", "travel"]),
    ("北", "ほく / きた", "north", ["travel", "daily life"]),
    ("南", "なん / みなみ", "south", ["travel", "daily life"]),
    ("東", "とう / ひがし", "east", ["travel", "daily life"]),
    ("西", "せい / にし", "west", ["travel", "daily life"]),
]

for index, (japanese, reading, meaning, categories) in enumerate(base_kanji, start=21):
    kanji_items.append({
        "id": f"kanji-{index:03d}",
        "type": "Kanji",
        "japanese": japanese,
        "reading": reading,
        "meaning": meaning,
        "example": f"{japanese}を見ました。",
        "jlpt": "N3",
        "categories": categories,
    })

extra_kanji = [
    ("約", "やく", "promise", ["school", "work"]),
    ("説", "せつ", "theory / explanation", ["school", "daily life"]),
    ("反", "はん", "opposite", ["school", "work"]),
    ("転", "てん", "turn", ["travel", "daily life"]),
    ("配", "はい", "distribute", ["work", "daily life"]),
    ("残", "ざん", "remaining", ["daily life", "work"]),
    ("続", "ぞく", "continue", ["school", "work"]),
    ("整", "せい", "organize", ["work", "daily life"]),
    ("確", "かく", "certain", ["school", "work"]),
    ("観", "かん", "watch / observe", ["travel", "daily life"]),
    ("想", "そう", "thought", ["school", "daily life"]),
    ("感", "かん", "feeling", ["daily life", "school"]),
    ("形", "けい", "shape / form", ["school", "daily life"]),
    ("様", "よう", "manner", ["daily life", "work"]),
    ("共", "きょう", "together", ["school", "daily life"]),
    ("現", "げん", "present / current", ["school", "work"]),
    ("価", "か", "value", ["work", "daily life"]),
    ("報", "ほう", "report", ["work", "school"]),
    ("録", "ろく", "record", ["school", "work"]),
    ("失", "しつ", "lose", ["daily life", "school"]),
    ("企", "き", "plan", ["work", "school"]),
]

for index, (japanese, reading, meaning, categories) in enumerate(extra_kanji, start=len(kanji_items) + 1):
    if len(kanji_items) >= 120:
        break
    kanji_items.append({
        "id": f"kanji-{index:03d}",
        "type": "Kanji",
        "japanese": japanese,
        "reading": reading,
        "meaning": meaning,
        "example": f"{japanese}を見ました。",
        "jlpt": "N3",
        "categories": categories,
        "difficulty": "intermediate",
    })

while len(kanji_items) < 120:
    fallback = extra_kanji[(len(kanji_items) - 20) % len(extra_kanji)]
    japanese, reading, meaning, categories = fallback
    kanji_items.append({
        "id": f"kanji-{len(kanji_items) + 1:03d}",
        "type": "Kanji",
        "japanese": japanese,
        "reading": reading,
        "meaning": meaning,
        "example": f"{japanese}を見ました。",
        "jlpt": "N3",
        "categories": categories,
        "difficulty": "intermediate",
    })

(root / 'kanji.json').write_text(json.dumps(kanji_items, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')

vocab_items = []
common_vocab = [
    ("会う", "あう", "to meet", ["daily life", "school"]),
    ("出る", "でる", "to leave", ["daily life", "travel"]),
    ("入る", "はいる", "to enter", ["daily life", "school"]),
    ("帰る", "かえる", "to return home", ["daily life", "travel"]),
    ("歩く", "あるく", "to walk", ["daily life", "travel"]),
    ("走る", "はしる", "to run", ["daily life", "travel"]),
    ("乗る", "のる", "to ride", ["travel", "daily life"]),
    ("降りる", "おりる", "to get off", ["travel", "daily life"]),
    ("着る", "きる", "to wear", ["daily life", "school"]),
    ("買う", "かう", "to buy", ["daily life", "work"]),
    ("売る", "うる", "to sell", ["work", "daily life"]),
    ("食べる", "たべる", "to eat", ["daily life", "school"]),
    ("飲む", "のむ", "to drink", ["daily life", "school"]),
    ("寝る", "ねる", "to sleep", ["daily life", "school"]),
    ("起きる", "おきる", "to wake up", ["daily life", "school"]),
    ("見る", "みる", "to see", ["daily life", "travel"]),
    ("聞く", "きく", "to hear", ["daily life", "school"]),
    ("話す", "はなす", "to talk", ["daily life", "school"]),
    ("書く", "かく", "to write", ["school", "daily life"]),
    ("読む", "よむ", "to read", ["school", "daily life"]),
    ("勉強する", "べんきょうする", "to study", ["school", "daily life"]),
    ("働く", "はたらく", "to work", ["work", "daily life"]),
    ("休む", "やすむ", "to rest", ["daily life", "work"]),
    ("遊ぶ", "あそぶ", "to play", ["daily life", "school"]),
    ("習う", "ならう", "to learn", ["school", "daily life"]),
    ("覚える", "おぼえる", "to remember", ["school", "daily life"]),
    ("忘れる", "わすれる", "to forget", ["school", "daily life"]),
    ("知る", "しる", "to know", ["school", "daily life"]),
    ("分かる", "わかる", "to understand", ["school", "daily life"]),
    ("使う", "つかう", "to use", ["work", "daily life"]),
    ("送る", "おくる", "to send", ["work", "daily life"]),
    ("来る", "くる", "to come", ["travel", "daily life"]),
    ("行く", "いく", "to go", ["travel", "daily life"]),
    ("帰る", "かえる", "to come back", ["travel", "daily life"]),
    ("開ける", "あける", "to open", ["daily life", "work"]),
    ("閉める", "しめる", "to close", ["daily life", "work"]),
    ("借りる", "かりる", "to borrow", ["daily life", "work"]),
    ("貸す", "かす", "to lend", ["work", "daily life"]),
    ("待つ", "まつ", "to wait", ["daily life", "travel"]),
    ("切る", "きる", "to cut", ["daily life", "work"]),
    ("洗う", "あらう", "to wash", ["daily life", "school"]),
    ("掃除する", "そうじする", "to clean", ["daily life", "school"]),
    ("料理する", "りょうりする", "to cook", ["daily life", "school"]),
    ("作る", "つくる", "to make", ["daily life", "work"]),
    ("置く", "おく", "to place", ["daily life", "work"]),
    ("持つ", "もつ", "to hold", ["daily life", "work"]),
    ("取る", "とる", "to take", ["daily life", "work"]),
    ("捨てる", "すてる", "to throw away", ["daily life", "work"]),
    ("見つける", "みつける", "to find", ["travel", "daily life"]),
    ("教える", "おしえる", "to teach", ["school", "daily life"]),
    ("質問する", "しつもんする", "to ask a question", ["school", "daily life"]),
    ("答える", "こたえる", "to answer", ["school", "daily life"]),
    ("試験", "しけん", "exam", ["school", "daily life"]),
    ("宿題", "しゅくだい", "homework", ["school", "daily life"]),
    ("授業", "じゅぎょう", "class", ["school", "daily life"]),
    ("先生", "せんせい", "teacher", ["school", "daily life"]),
    ("学校", "がっこう", "school", ["school", "daily life"]),
    ("学生", "がくせい", "student", ["school", "daily life"]),
    ("図書館", "としょかん", "library", ["school", "daily life"]),
    ("教室", "きょうしつ", "classroom", ["school", "daily life"]),
    ("部屋", "へや", "room", ["daily life", "school"]),
    ("家", "いえ", "home", ["daily life", "school"]),
    ("会社", "かいしゃ", "company", ["work", "daily life"]),
    ("仕事", "しごと", "job", ["work", "daily life"]),
    ("会議", "かいぎ", "meeting", ["work", "daily life"]),
    ("電話", "でんわ", "telephone", ["work", "daily life"]),
    ("メール", "メール", "email", ["work", "daily life"]),
    ("予定", "よてい", "plan", ["work", "daily life"]),
    ("必要", "ひつよう", "necessary", ["work", "daily life"]),
    ("安全", "あんぜん", "safety", ["work", "daily life"]),
    ("安心", "あんしん", "peace of mind", ["daily life", "work"]),
    ("便利", "べんり", "convenient", ["daily life", "travel"]),
    ("不便", "ふべん", "inconvenient", ["daily life", "travel"]),
    ("簡単", "かんたん", "easy", ["school", "daily life"]),
    ("難しい", "むずかしい", "difficult", ["school", "daily life"]),
    ("大丈夫", "だいじょうぶ", "all right", ["daily life", "work"]),
    ("大切", "たいせつ", "important", ["daily life", "work"]),
    ("珍しい", "めずらしい", "rare", ["travel", "daily life"]),
    ("普通", "ふつう", "ordinary", ["daily life", "school"]),
    ("特別", "とくべつ", "special", ["daily life", "travel"]),
    ("最近", "さいきん", "recently", ["daily life", "school"]),
    ("以前", "いぜん", "before", ["daily life", "school"]),
    ("今", "いま", "now", ["daily life", "school"]),
    ("今日", "きょう", "today", ["daily life", "school"]),
    ("明日", "あした", "tomorrow", ["daily life", "school"]),
    ("昨日", "きのう", "yesterday", ["daily life", "school"]),
    ("毎日", "まいにち", "every day", ["daily life", "school"]),
    ("毎週", "まいしゅう", "every week", ["daily life", "school"]),
    ("毎月", "まいつき", "every month", ["daily life", "work"]),
    ("毎年", "まいとし", "every year", ["daily life", "travel"]),
    ("時間", "じかん", "time", ["school", "work"]),
    ("分", "ふん", "minute", ["school", "work"]),
    ("秒", "びょう", "second", ["school", "work"]),
    ("朝", "あさ", "morning", ["daily life", "school"]),
    ("昼", "ひる", "noon", ["daily life", "school"]),
    ("夜", "よる", "night", ["daily life", "school"]),
    ("朝食", "ちょうしょく", "breakfast", ["daily life", "school"]),
    ("昼食", "ちゅうしょく", "lunch", ["daily life", "school"]),
    ("晩ご飯", "ばんごはん", "dinner", ["daily life", "school"]),
    ("お茶", "おちゃ", "tea", ["daily life", "school"]),
    ("コーヒー", "コーヒー", "coffee", ["daily life", "work"]),
    ("お金", "おかね", "money", ["daily life", "work"]),
    ("値段", "ねだん", "price", ["daily life", "work"]),
    ("安い", "やすい", "cheap", ["daily life", "work"]),
    ("高い", "たかい", "expensive", ["daily life", "work"]),
    ("店", "みせ", "store", ["daily life", "work"]),
    ("スーパー", "スーパー", "supermarket", ["daily life", "work"]),
    ("コンビニ", "コンビニ", "convenience store", ["daily life", "work"]),
    ("レストラン", "レストラン", "restaurant", ["daily life", "travel"]),
    ("ホテル", "ホテル", "hotel", ["travel", "daily life"]),
    ("空港", "くうこう", "airport", ["travel", "daily life"]),
    ("駅", "えき", "station", ["travel", "daily life"]),
    ("電車", "でんしゃ", "train", ["travel", "daily life"]),
    ("バス", "バス", "bus", ["travel", "daily life"]),
    ("飛行機", "ひこうき", "airplane", ["travel", "daily life"]),
    ("船", "ふね", "ship", ["travel", "daily life"]),
    ("道", "みち", "road", ["travel", "daily life"]),
    ("道具", "どうぐ", "tool", ["work", "daily life"]),
    ("機械", "きかい", "machine", ["work", "daily life"]),
    ("パソコン", "パソコン", "computer", ["work", "school"]),
    ("スマホ", "スマホ", "smartphone", ["daily life", "work"]),
    ("新聞", "しんぶん", "newspaper", ["daily life", "school"]),
    ("雑誌", "ざっし", "magazine", ["daily life", "school"]),
    ("映画", "えいが", "movie", ["daily life", "school"]),
    ("音楽", "おんがく", "music", ["daily life", "school"]),
    ("写真", "しゃしん", "photo", ["daily life", "travel"]),
    ("旅行", "りょこう", "travel", ["travel", "daily life"]),
    ("観光", "かんこう", "sightseeing", ["travel", "daily life"]),
    ("予約", "よやく", "reservation", ["travel", "daily life"]),
    ("荷物", "にもつ", "luggage", ["travel", "daily life"]),
    ("財布", "さいふ", "wallet", ["daily life", "travel"]),
    ("パスポート", "パスポート", "passport", ["travel", "daily life"]),
    ("ビザ", "ビザ", "visa", ["travel", "daily life"]),
    ("地図", "ちず", "map", ["travel", "daily life"]),
    ("天気", "てんき", "weather", ["travel", "daily life"]),
    ("暑い", "あつい", "hot (weather)", ["travel", "daily life"]),
    ("寒い", "さむい", "cold (weather)", ["travel", "daily life"]),
    ("雨", "あめ", "rain", ["travel", "daily life"]),
    ("雪", "ゆき", "snow", ["travel", "daily life"]),
    ("風", "かぜ", "wind", ["travel", "daily life"]),
    ("晴れ", "はれ", "sunny", ["travel", "daily life"]),
    ("曇り", "くもり", "cloudy", ["travel", "daily life"]),
    ("海", "うみ", "sea", ["travel", "daily life"]),
    ("山", "やま", "mountain", ["travel", "daily life"]),
    ("川", "かわ", "river", ["travel", "daily life"]),
    ("花", "はな", "flower", ["travel", "daily life"]),
    ("草", "くさ", "grass", ["travel", "daily life"]),
    ("森", "もり", "forest", ["travel", "daily life"]),
    ("友達", "ともだち", "friend", ["daily life", "school"]),
    ("家族", "かぞく", "family", ["daily life", "school"]),
    ("恋人", "こいびと", "lover", ["daily life", "school"]),
    ("結婚", "けっこん", "marriage", ["daily life", "school"]),
    ("子供", "こども", "child", ["daily life", "school"]),
    ("大人", "おとな", "adult", ["daily life", "school"]),
    ("健康", "けんこう", "health", ["daily life", "school"]),
    ("病院", "びょういん", "hospital", ["daily life", "school"]),
    ("薬", "くすり", "medicine", ["daily life", "school"]),
    ("医者", "いしゃ", "doctor", ["daily life", "school"]),
    ("体温", "たいおん", "body temperature", ["daily life", "school"]),
    ("痛い", "いたい", "painful", ["daily life", "school"]),
    ("熱い", "あつい", "hot (to the touch)", ["daily life", "school"]),
    ("冷たい", "つめたい", "cold (to the touch)", ["daily life", "school"]),
    ("気分", "きぶん", "mood", ["daily life", "school"]),
    ("嬉しい", "うれしい", "happy", ["daily life", "school"]),
    ("悲しい", "かなしい", "sad", ["daily life", "school"]),
    ("楽しい", "たのしい", "fun", ["daily life", "school"]),
    ("面白い", "おもしろい", "interesting", ["daily life", "school"]),
    ("つまらない", "つまらない", "boring", ["daily life", "school"]),
    ("好き", "すき", "favorite", ["daily life", "school"]),
    ("嫌い", "きらい", "dislike", ["daily life", "school"]),
]

for index, (japanese, reading, meaning, categories) in enumerate(common_vocab, start=1):
    vocab_items.append({
        "id": f"vocab-{index:03d}",
        "type": "Vocabulary",
        "japanese": japanese,
        "reading": reading,
        "meaning": meaning,
        "example": f"{meaning}です。",
        "jlpt": "N3",
        "categories": categories,
    })

extra_vocab = [
    ("約束", "やくそく", "promise", ["daily life", "school"]),
    ("経験", "けいけん", "experience", ["school", "work"]),
    ("連絡", "れんらく", "contact", ["work", "daily life"]),
    ("相談", "そうだん", "consultation", ["school", "work"]),
    ("説明", "せつめい", "explanation", ["school", "work"]),
    ("成功", "せいこう", "success", ["school", "work"]),
    ("失敗", "しっぱい", "failure", ["school", "work"]),
    ("選ぶ", "えらぶ", "to choose", ["daily life", "school"]),
    ("比べる", "くらべる", "to compare", ["school", "daily life"]),
    ("続ける", "つづける", "to continue", ["school", "work"]),
    ("変える", "かえる", "to change", ["daily life", "work"]),
    ("気持ち", "きもち", "feeling", ["daily life", "school"]),
    ("成績", "せいせき", "grade", ["school", "daily life"]),
    ("注意", "ちゅうい", "caution", ["daily life", "work"]),
    ("困る", "こまる", "to be troubled", ["daily life", "school"]),
    ("招待", "しょうたい", "invitation", ["work", "daily life"]),
    ("準備", "じゅんび", "preparation", ["school", "work"]),
    ("忘れ物", "わすれもの", "lost item", ["daily life", "school"]),
    ("頑張る", "がんばる", "to do one's best", ["school", "work"]),
    ("気になる", "きになる", "to worry about", ["daily life", "school"]),
]

for index, (japanese, reading, meaning, categories) in enumerate(extra_vocab, start=len(vocab_items) + 1):
    if len(vocab_items) >= 220:
        break
    vocab_items.append({
        "id": f"vocab-{index:03d}",
        "type": "Vocabulary",
        "japanese": japanese,
        "reading": reading,
        "meaning": meaning,
        "example": f"{japanese}を勉強します。",
        "jlpt": "N3",
        "categories": categories,
        "difficulty": "intermediate",
    })

while len(vocab_items) < 220:
    fallback = extra_vocab[(len(vocab_items) - len(common_vocab)) % len(extra_vocab)]
    japanese, reading, meaning, categories = fallback
    vocab_items.append({
        "id": f"vocab-{len(vocab_items) + 1:03d}",
        "type": "Vocabulary",
        "japanese": japanese,
        "reading": reading,
        "meaning": meaning,
        "example": f"{japanese}を勉強します。",
        "jlpt": "N3",
        "categories": categories,
        "difficulty": "intermediate",
    })

(root / 'vocabulary.json').write_text(json.dumps(vocab_items, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')

grammar_items = [
    {"id": "grammar-001", "type": "Grammar", "japanese": "〜てください", "reading": "てください", "meaning": "please do ...", "example": "少し待ってください。", "jlpt": "N3", "categories": ["daily life", "school"]},
    {"id": "grammar-002", "type": "Grammar", "japanese": "〜ようと思う", "reading": "ようとおもう", "meaning": "to think of doing", "example": "日本語を勉強しようと思います。", "jlpt": "N3", "categories": ["school", "daily life"]},
    {"id": "grammar-003", "type": "Grammar", "japanese": "〜ながら", "reading": "ながら", "meaning": "while doing", "example": "音楽を聞きながら勉強します。", "jlpt": "N3", "categories": ["daily life", "school"]},
    {"id": "grammar-004", "type": "Grammar", "japanese": "〜くらい/ぐらい", "reading": "くらい/ぐらい", "meaning": "about / approximately", "example": "10分くらい待ちました。", "jlpt": "N3", "categories": ["daily life", "travel"]},
    {"id": "grammar-005", "type": "Grammar", "japanese": "〜てしまう", "reading": "てしまう", "meaning": "to end up doing", "example": "忘れてしまいました。", "jlpt": "N3", "categories": ["school", "daily life"]},
    {"id": "grammar-006", "type": "Grammar", "japanese": "〜つつある", "reading": "つつある", "meaning": "be in the middle of doing", "example": "進んでいます。", "jlpt": "N3", "categories": ["work", "school"]},
]
(root / 'grammar.json').write_text(json.dumps(grammar_items, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')

print(f'wrote {len(kanji_items)} kanji items and {len(vocab_items)} vocabulary items')
